In [1]:
import os
from datetime import datetime
from multitask_trainer import train_eval_model

## E5+LoRa

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"]="1"
model_path = "intfloat/multilingual-e5-large"
cache_dir = '../cache'

def get_experiment_config(input_model_name):
    return [
        ("../augmentation/augmented_data_2/lith_dataset_augmented_groups_full", f"outputs/lith_classifier_{input_model_name}_lora_grouped_augmented")
    ]

exp_config = get_experiment_config("e5")
lora_args = {
    "init_lora_weights": "olora",
    "target_modules": "all-linear"
}
batch_size = 32

In [3]:
print("Training started:", datetime.now())

Training started: 2026-05-15 21:34:42.829664

In [4]:
for data_dir, model_dir in exp_config:
    print(f"Training E5 classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training E5 classifier for data ../augmentation/augmented_data_2/lith_dataset_augmented_groups_full

Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at intfloat/multilingual-e5-large and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
***** Running training *****
  Num examples = 17,268
  Num Epochs = 20
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 10,800
  Number of trainable parameters = 3,565,588

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-2548] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-4368] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-1080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2700
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-1620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3240
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-2160] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3780
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-2700] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4320
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-3780] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4860
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-4320] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5400
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-3240] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5940
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-4860] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6480
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-5400] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-7020
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-5940] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-7560
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-6480] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-8100
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-7020] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-8640
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-7560] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-9180
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-8640] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-9720
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-9180] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-10260

sexuality
              precision    recall  f1-score   support

           0       0.98      0.93      0.95       185
           1       0.93      0.98      0.95       184

    accuracy                           0.95       369
   macro avg       0.95      0.95      0.95       369
weighted avg       0.96      0.95      0.95       369

religion
              precision    recall  f1-score   support

           0       0.95      0.86      0.91       183
           1       0.88      0.96      0.91       183

    accuracy                           0.91       366
   macro avg       0.91      0.91      0.91       366
weighted avg       0.91      0.91      0.91       366

country
              precision    recall  f1-score   support

           0       0.97      0.89      0.93        93
           1       0.90      0.97      0.93        94

    accuracy                           0.93       187
   macro avg       0.93      0.93      0.93       187
weighted avg       0.93      0.93      0.93       187

race
              precision    recall  f1-score   support

           0       0.96      0.87      0.91       360
           1       0.88      0.96      0.92       361

    accuracy                           0.92       721
   macro avg       0.92      0.92      0.92       721
weighted avg       0.92      0.92      0.92       721

politics
              precision    recall  f1-score   support

           0       0.95      0.89      0.92       500
           1       0.90      0.96      0.93       499

    accuracy                           0.92       999
   macro avg       0.93      0.92      0.92       999
weighted avg       0.93      0.92      0.92       999

tokenizer config file saved in outputs/lith_classifier_e5_lora_grouped_augmented/tokenizer_config.json
Special tokens file saved in outputs/lith_classifier_e5_lora_grouped_augmented/special_tokens_map.json
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.953930  0.954907   0.932642  0.978261  0.907871  0.953995
1   religion  0.909836  0.913838   0.875000  0.956284  0.819672  0.909836
2    country  0.930481  0.933333   0.900990  0.968085  0.860903  0.930279
3       race  0.916782  0.920424   0.882952  0.961219  0.833544  0.916721
4   politics  0.923924  0.926357   0.896811  0.957916  0.847858  0.923958

In [5]:
print("Training finished:", datetime.now())

Training finished: 2026-05-16 00:09:29.889327

## LaBSE+Lora

In [6]:
model_path = "sentence-transformers/LaBSE"
exp_config = get_experiment_config("labse")

In [7]:
for data_dir, model_dir in exp_config:
    print(f"Training LaBSE classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training LaBSE classifier for data ../augmentation/augmented_data_2/lith_dataset_augmented_groups_full

loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading file vocab.txt from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/vocab.txt
loading file tokenizer.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/special_tokens_map.json
loading file tokenizer_config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading weights file model.safetensors from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/model.safetensors
All model checkpoint weights were used when initializing BertMultiTaskClassifier.

Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at sentence-transformers/LaBSE and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
PyTorch: setting up devices
average_tokens_across_devices is True but world size is 1. Setting it to False automatically.
***** Running training *****
  Num examples = 17,268
  Num Epochs = 20
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 10,800
  Number of trainable parameters = 1,347,092

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-10260] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-10800] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-1080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2700
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-1620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3240
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-2160] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3780
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-2700] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4320
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-3240] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4860
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-3780] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5400
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-4320] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5940
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-4860] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6480
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-5400] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-7020
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-6480] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-7560
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-7020] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-8100
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-5940] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-8640
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-7560] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-9180
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,

tokenizer config file saved in outputs/lith_classifier_labse_lora_grouped_augmented/tokenizer_config.json

sexuality
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       185
           1       0.96      0.95      0.95       184

    accuracy                           0.95       369
   macro avg       0.95      0.95      0.95       369
weighted avg       0.95      0.95      0.95       369

religion
              precision    recall  f1-score   support

           0       0.95      0.87      0.91       183
           1       0.88      0.96      0.92       183

    accuracy                           0.91       366
   macro avg       0.92      0.91      0.91       366
weighted avg       0.92      0.91      0.91       366

country
              precision    recall  f1-score   support

           0       0.96      0.91      0.93        93
           1       0.92      0.96      0.94        94

    accuracy                           0.94       187
   macro avg       0.94      0.94      0.94       187
weighted avg       0.94      0.94      0.94       187

race
              precision    recall  f1-score   support

           0       0.91      0.89      0.90       360
           1       0.89      0.91      0.90       361

    accuracy                           0.90       721
   macro avg       0.90      0.90      0.90       721
weighted avg       0.90      0.90      0.90       721

politics
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       500
           1       0.88      0.93      0.90       499

    accuracy                           0.90       999
   macro avg       0.90      0.90      0.90       999
weighted avg       0.90      0.90      0.90       999

Special tokens file saved in outputs/lith_classifier_labse_lora_grouped_augmented/special_tokens_map.json
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.953930  0.953678   0.956284  0.951087  0.907857  0.953922
1   religion  0.912568  0.916230   0.879397  0.956284  0.825137  0.912568
2    country  0.935829  0.937500   0.918367  0.957447  0.871625  0.935713
3       race  0.902913  0.904110   0.894309  0.914127  0.805819  0.902897
4   politics  0.901902  0.904297   0.881905  0.927856  0.803814  0.901928

## LitLatBERT + LORA

In [8]:
model_path = "EMBEDDIA/litlat-bert"
exp_config = get_experiment_config("litlatbert")

In [9]:
print("Training started:", datetime.now())

Training started: 2026-05-16 01:03:54.871854

In [10]:
for data_dir, model_dir in exp_config:
    print(f"Training LiLatBERT classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  output_dir="outputs-train/litlatbert-lora-large",
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  tokenizer_args=dict(padding='max_length', truncation=True, max_length=512),
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training LiLatBERT classifier for data ../augmentation/augmented_data_2/lith_dataset_augmented_groups_full

loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading file sentencepiece.bpe.model from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/sentencepiece.bpe.model
loading file tokenizer.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/special_tokens_map.json
loading file tokenizer_config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading weights file pytorch_model.bin from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/pytorch_model.bin
Attempting to create safetensors variant
Safetensors PR exists
Some weights of the model checkpoint at EMBEDDIA/litlat-bert were not used when initializing BertMultiTaskClassifier: ['lm_head.bias', 'lm_head.decoder.bias', 'lm_head.decoder.weight', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.position_embeddings.weight', 'roberta.embeddings.token_type_embeddings.weight', 'roberta.embeddings.word_embeddings.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.dense.bias', 'roberta.encoder.layer.0.attention.output.dense.weight', 'roberta.encoder.layer.0.attention.self.key.bias', 'roberta.encoder.layer.0.attention.self.key.weight', 'roberta.encoder.layer.0.attention.self.query.bias', 'roberta.encoder.layer.0.attention.self.query.weight', 'roberta.encoder.layer.0.attention.self.value.bias', 'roberta.encoder.layer.0.attention.self.value.weight', 'roberta.encoder.layer.0.intermediate.dense.bias', 'roberta.encoder.layer.0.intermediate.dense.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.dense.bias', 'roberta.encoder.layer.0.output.dense.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.dense.bias', 'roberta.encoder.layer.1.attention.output.dense.weight', 'roberta.encoder.layer.1.attention.self.key.bias', 'roberta.encoder.layer.1.attention.self.key.weight', 'roberta.encoder.layer.1.attention.self.query.bias', 'roberta.encoder.layer.1.attention.self.query.weight', 'roberta.encoder.layer.1.attention.self.value.bias', 'roberta.encoder.layer.1.attention.self.value.weight', 'roberta.encoder.layer.1.intermediate.dense.bias', 'roberta.encoder.layer.1.intermediate.dense.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.dense.bias', 'roberta.encoder.layer.1.output.dense.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.dense.bias', 'roberta.encoder.layer.10.attention.output.dense.weight', 'roberta.encoder.layer.10.attention.self.key.bias', 'roberta.encoder.layer.10.attention.self.key.weight', 'roberta.encoder.layer.10.attention.self.query.bias', 'roberta.encoder.layer.10.attention.self.query.weight', 'roberta.encoder.layer.10.attention.self.value.bias', 'roberta.encoder.layer.10.attention.self.value.weight', 'roberta.encoder.layer.10.intermediate.dense.bias', 'roberta.encoder.layer.10.intermediate.dense.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.dense.bias', 'roberta.encoder.layer.10.output.dense.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.dense.bias', 'roberta.encoder.layer.11.attention.output.dense.weight', 'roberta.encoder.layer.11.attention.self.key.bias', 'roberta.encoder.layer.11.attention.self.key.weight', 'roberta.encoder.layer.11.attention.self.query.bias', 'roberta.encoder.layer.11.attention.self.query.weight', 'roberta.encoder.layer.11.attention.self.value.bias', 'roberta.encoder.layer.11.attention.self.value.weight', 'roberta.encoder.layer.11.intermediate.dense.bias', 'roberta.encoder.layer.11.intermediate.dense.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.dense.bias', 'roberta.encoder.layer.11.output.dense.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.dense.bias', 'roberta.encoder.layer.2.attention.output.dense.weight', 'roberta.encoder.layer.2.attention.self.key.bias', 'roberta.encoder.layer.2.attention.self.key.weight', 'roberta.encoder.layer.2.attention.self.query.bias', 'roberta.encoder.layer.2.attention.self.query.weight', 'roberta.encoder.layer.2.attention.self.value.bias', 'roberta.encoder.layer.2.attention.self.value.weight', 'roberta.encoder.layer.2.intermediate.dense.bias', 'roberta.encoder.layer.2.intermediate.dense.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.dense.bias', 'roberta.encoder.layer.2.output.dense.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.dense.bias', 'roberta.encoder.layer.3.attention.output.dense.weight', 'roberta.encoder.layer.3.attention.self.key.bias', 'roberta.encoder.layer.3.attention.self.key.weight', 'roberta.encoder.layer.3.attention.self.query.bias', 'roberta.encoder.layer.3.attention.self.query.weight', 'roberta.encoder.layer.3.attention.self.value.bias', 'roberta.encoder.layer.3.attention.self.value.weight', 'roberta.encoder.layer.3.intermediate.dense.bias', 'roberta.encoder.layer.3.intermediate.dense.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.dense.bias', 'roberta.encoder.layer.3.output.dense.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.dense.bias', 'roberta.encoder.layer.4.attention.output.dense.weight', 'roberta.encoder.layer.4.attention.self.key.bias', 'roberta.encoder.layer.4.attention.self.key.weight', 'roberta.encoder.layer.4.attention.self.query.bias', 'roberta.encoder.layer.4.attention.self.query.weight', 'roberta.encoder.layer.4.attention.self.value.bias', 'roberta.encoder.layer.4.attention.self.value.weight', 'roberta.encoder.layer.4.intermediate.dense.bias', 'roberta.encoder.layer.4.intermediate.dense.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.dense.bias', 'roberta.encoder.layer.4.output.dense.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.dense.bias', 'roberta.encoder.layer.5.attention.output.dense.weight', 'roberta.encoder.layer.5.attention.self.key.bias', 'roberta.encoder.layer.5.attention.self.key.weight', 'roberta.encoder.layer.5.attention.self.query.bias', 'roberta.encoder.layer.5.attention.self.query.weight', 'roberta.encoder.layer.5.attention.self.value.bias', 'roberta.encoder.layer.5.attention.self.value.weight', 'roberta.encoder.layer.5.intermediate.dense.bias', 'roberta.encoder.layer.5.intermediate.dense.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.dense.bias', 'roberta.encoder.layer.5.output.dense.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.dense.bias', 'roberta.encoder.layer.6.attention.output.dense.weight', 'roberta.encoder.layer.6.attention.self.key.bias', 'roberta.encoder.layer.6.attention.self.key.weight', 'roberta.encoder.layer.6.attention.self.query.bias', 'roberta.encoder.layer.6.attention.self.query.weight', 'roberta.encoder.layer.6.attention.self.value.bias', 'roberta.encoder.layer.6.attention.self.value.weight', 'roberta.encoder.layer.6.intermediate.dense.bias', 'roberta.encoder.layer.6.intermediate.dense.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.dense.bias', 'roberta.encoder.layer.6.output.dense.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.dense.bias', 'roberta.encoder.layer.7.attention.output.dense.weight', 'roberta.encoder.layer.7.attention.self.key.bias', 'roberta.encoder.layer.7.attention.self.key.weight', 'roberta.encoder.layer.7.attention.self.query.bias', 'roberta.encoder.layer.7.attention.self.query.weight', 'roberta.encoder.layer.7.attention.self.value.bias', 'roberta.encoder.layer.7.attention.self.value.weight', 'roberta.encoder.layer.7.intermediate.dense.bias', 'roberta.encoder.layer.7.intermediate.dense.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.dense.bias', 'roberta.encoder.layer.7.output.dense.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.dense.bias', 'roberta.encoder.layer.8.attention.output.dense.weight', 'roberta.encoder.layer.8.attention.self.key.bias', 'roberta.encoder.layer.8.attention.self.key.weight', 'roberta.encoder.layer.8.attention.self.query.bias', 'roberta.encoder.layer.8.attention.self.query.weight', 'roberta.encoder.layer.8.attention.self.value.bias', 'roberta.encoder.layer.8.attention.self.value.weight', 'roberta.encoder.layer.8.intermediate.dense.bias', 'roberta.encoder.layer.8.intermediate.dense.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.dense.bias', 'roberta.encoder.layer.8.output.dense.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.dense.bias', 'roberta.encoder.layer.9.attention.output.dense.weight', 'roberta.encoder.layer.9.attention.self.key.bias', 'roberta.encoder.layer.9.attention.self.key.weight', 'roberta.encoder.layer.9.attention.self.query.bias', 'roberta.encoder.layer.9.attention.self.query.weight', 'roberta.encoder.layer.9.attention.self.value.bias', 'roberta.encoder.layer.9.attention.self.value.weight', 'roberta.encoder.layer.9.intermediate.dense.bias', 'roberta.encoder.layer.9.intermediate.dense.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.dense.bias', 'roberta.encoder.layer.9.output.dense.weight', 'roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing BertMultiTaskClassifier from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertMultiTaskClassifier from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-6916] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-1080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-7280] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-1620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-2160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-1080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-2700
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-1620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-3240
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-2160] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-3780
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-2700] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-4320
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-3240] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-4860
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-3780] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-5400
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-4320] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-5940
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-4860] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-6480
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-5400] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-7020
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-5940] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-7560
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-6480] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-8100
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-7020] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-8640
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-7560] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-9180
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-8100] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-9720
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-8640] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-10260
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {

tokenizer config file saved in outputs/lith_classifier_litlatbert_lora_grouped_augmented/tokenizer_config.json
Special tokens file saved in outputs/lith_classifier_litlatbert_lora_grouped_augmented/special_tokens_map.json

sexuality
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       185
           1       0.84      0.81      0.82       184

    accuracy                           0.83       369
   macro avg       0.83      0.83      0.83       369
weighted avg       0.83      0.83      0.83       369

religion
              precision    recall  f1-score   support

           0       0.71      0.51      0.59       183
           1       0.62      0.79      0.69       183

    accuracy                           0.65       366
   macro avg       0.66      0.65      0.64       366
weighted avg       0.66      0.65      0.64       366

country
              precision    recall  f1-score   support

           0       0.77      0.68      0.72        93
           1       0.71      0.80      0.75        94

    accuracy                           0.74       187
   macro avg       0.74      0.74      0.74       187
weighted avg       0.74      0.74      0.74       187

race
              precision    recall  f1-score   support

           0       0.69      0.52      0.59       360
           1       0.62      0.76      0.68       361

    accuracy                           0.64       721
   macro avg       0.65      0.64      0.64       721
weighted avg       0.65      0.64      0.64       721

politics
              precision    recall  f1-score   support

           0       0.68      0.52      0.59       500
           1       0.61      0.76      0.68       499

    accuracy                           0.64       999
   macro avg       0.65      0.64      0.63       999
weighted avg       0.65      0.64      0.63       999

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.826558  0.823204   0.837079  0.809783  0.653083  0.826513
1   religion  0.650273  0.693780   0.617021  0.792350  0.300546  0.650273
2    country  0.737968  0.753769   0.714286  0.797872  0.475591  0.737646
3       race  0.642164  0.680693   0.615213  0.761773  0.284089  0.641998
4   politics  0.637638  0.676208   0.610662  0.757515  0.275449  0.637758

In [11]:
print("Training finished:", datetime.now())

Training finished: 2026-05-16 01:58:42.590128