In [1]:
import os
from datetime import datetime
from multitask_trainer import train_eval_model

## E5+LoRa

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"]="1"
model_path = "intfloat/multilingual-e5-large"
cache_dir = '../cache'

def get_experiment_config(input_model_name):
    return [
        ("data/lith_dataset_balanced_groups_full_multi", f"outputs/lith_classifier_{input_model_name}_lora_balanced_groups_full")
    ]

exp_config = get_experiment_config("e5")
lora_args = {
    "init_lora_weights": "olora",
    "target_modules": "all-linear"
}
batch_size = 32

In [3]:
print("Training started:", datetime.now())

Training started: 2026-03-18 08:25:24.160508

In [4]:
for data_dir, model_dir in exp_config:
    print(f"Training E5 classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training E5 classifier for data data/lith_dataset_balanced_groups_full_multi

Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at intfloat/multilingual-e5-large and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026/03/18 08:25:29 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/03/18 08:25:29 INFO mlflow.store.db.utils: Updating database tables
***** Running training *****
  Num examples = 12,320
  Num Epochs = 20
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 7,700
  Number of trainable parameters = 3,565,588

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-385
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-13068] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-770
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-14520] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1155
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-385] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-770] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1925
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-1540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2310
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-1155] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2695
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-1925] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-2310] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3465
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-2695] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3850
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-3080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4235
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-3465] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-3850] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5005
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-4235] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5390
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-5005] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5775
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-4620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-5390] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6545
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-5775] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6930
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Deleting older checkpoint [test-classifier/checkpoint-6545] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-7315

sexuality
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       185
           1       0.97      0.95      0.96       184

    accuracy                           0.96       369
   macro avg       0.96      0.96      0.96       369
weighted avg       0.96      0.96      0.96       369

religion
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       183
           1       0.90      0.92      0.91       183

    accuracy                           0.91       366
   macro avg       0.91      0.91      0.91       366
weighted avg       0.91      0.91      0.91       366

country
              precision    recall  f1-score   support

           0       0.88      0.94      0.91        93
           1       0.93      0.87      0.90        94

    accuracy                           0.90       187
   macro avg       0.91      0.90      0.90       187
weighted avg       0.91      0.90      0.90       187

race
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       360
           1       0.93      0.93      0.93       361

    accuracy                           0.93       721
   macro avg       0.93      0.93      0.93       721
weighted avg       0.93      0.93      0.93       721

politics
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       500
           1       0.90      0.93      0.91       499

    accuracy                           0.91       999
   macro avg       0.91      0.91      0.91       999
weighted avg       0.91      0.91      0.91       999

tokenizer config file saved in outputs/lith_classifier_e5_lora_balanced_groups_full/tokenizer_config.json
Special tokens file saved in outputs/lith_classifier_e5_lora_balanced_groups_full/special_tokens_map.json
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.956640  0.956044   0.966667  0.945652  0.913273  0.956610
1   religion  0.909836  0.911051   0.898936  0.923497  0.819672  0.909836
2    country  0.903743  0.901099   0.931818  0.872340  0.807547  0.903912
3       race  0.929265  0.929655   0.925824  0.933518  0.858528  0.929259
4   politics  0.910911  0.912142   0.898833  0.925852  0.821827  0.910926

In [5]:
print("Training finished:", datetime.now())

Training finished: 2026-03-18 10:47:11.739867

## LaBSE+Lora

In [6]:
model_path = "sentence-transformers/LaBSE"
exp_config = get_experiment_config("labse")

In [7]:
for data_dir, model_dir in exp_config:
    print(f"Training LaBSE classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training LaBSE classifier for data data/lith_dataset_balanced_groups_full_multi

loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading file vocab.txt from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/vocab.txt
loading file tokenizer.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/special_tokens_map.json
loading file tokenizer_config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading configuration file config.json from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

loading weights file model.safetensors from cache at ../cache/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/model.safetensors
All model checkpoint weights were used when initializing BertMultiTaskClassifier.

Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at sentence-transformers/LaBSE and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
PyTorch: setting up devices
average_tokens_across_devices is True but world size is 1. Setting it to False automatically.
***** Running training *****
  Num examples = 12,320
  Num Epochs = 20
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 7,700
  Number of trainable parameters = 1,347,092

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-385
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-6160] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-770
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-7700] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1155
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-385] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-770] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-1925
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-1155] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2310
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-1540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-2695
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-1925] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-2695] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3465
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-3080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-3850
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-3465] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4235
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-2310] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-4620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-3850] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5005
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-4235] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5390
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-4620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-5775
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-5005] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

Deleting older checkpoint [test-classifier/checkpoint-5775] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to test-classifier/checkpoint-6545
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,

sexuality
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       185
           1       0.97      0.95      0.96       184

    accuracy                           0.96       369
   macro avg       0.96      0.96      0.96       369
weighted avg       0.96      0.96      0.96       369

religion
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       183
           1       0.91      0.94      0.93       183

    accuracy                           0.93       366
   macro avg       0.93      0.93      0.93       366
weighted avg       0.93      0.93      0.93       366

country
              precision    recall  f1-score   support

           0       0.93      0.95      0.94        93
           1       0.95      0.93      0.94        94

    accuracy                           0.94       187
   macro avg       0.94      0.94      0.94       187
weighted avg       0.94      0.94      0.94       187

race
              precision    recall  f1-score   support

           0       0.90      0.91      0.91       360
           1       0.91      0.90      0.91       361

    accuracy                           0.91       721
   macro avg       0.91      0.91      0.91       721
weighted avg       0.91      0.91      0.91       721

politics
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       500
           1       0.90      0.92      0.91       499

    accuracy                           0.91       999
   macro avg       0.91      0.91      0.91       999
weighted avg       0.91      0.91      0.91       999

tokenizer config file saved in outputs/lith_classifier_labse_lora_balanced_groups_full/tokenizer_config.json
Special tokens file saved in outputs/lith_classifier_labse_lora_balanced_groups_full/special_tokens_map.json
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--sentence-transformers--LaBSE/snapshots/836121a0533e5664b21c7aacc5d22951f2b8b25b/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 501153
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.956640  0.956044   0.966667  0.945652  0.913273  0.956610
1   religion  0.926230  0.927224   0.914894  0.939891  0.852459  0.926230
2    country  0.935829  0.935484   0.945652  0.925532  0.871669  0.935884
3       race  0.908460  0.908078   0.913165  0.903047  0.816923  0.908468
4   politics  0.907908  0.908911   0.898239  0.919840  0.815820  0.907920

## LitLatBERT + LORA

In [8]:
model_path = "EMBEDDIA/litlat-bert"
exp_config = get_experiment_config("litlatbert")

In [9]:
print("Training started:", datetime.now())

Training started: 2026-03-18 11:47:20.152303

In [10]:
for data_dir, model_dir in exp_config:
    print(f"Training LiLatBERT classifier for data {data_dir}")
    _, results = train_eval_model(model_path, data_dir, cache_dir=cache_dir, save_model_dir=model_dir, 
                                  output_dir="outputs-train/litlatbert-lora-large",
                                  batch_size=batch_size, num_epochs=20, eval_batch_size=128, 
                                  tokenizer_args=dict(padding='max_length', truncation=True, max_length=512),
                                  use_lora=True, lora_args=lora_args)
    print(results)

Training LiLatBERT classifier for data data/lith_dataset_balanced_groups_full_multi

loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading file sentencepiece.bpe.model from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/sentencepiece.bpe.model
loading file tokenizer.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/special_tokens_map.json
loading file tokenizer_config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading configuration file config.json from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

loading weights file pytorch_model.bin from cache at ../cache/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/pytorch_model.bin
Attempting to create safetensors variant
Safetensors PR exists
Some weights of the model checkpoint at EMBEDDIA/litlat-bert were not used when initializing BertMultiTaskClassifier: ['lm_head.bias', 'lm_head.decoder.bias', 'lm_head.decoder.weight', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.position_embeddings.weight', 'roberta.embeddings.token_type_embeddings.weight', 'roberta.embeddings.word_embeddings.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.dense.bias', 'roberta.encoder.layer.0.attention.output.dense.weight', 'roberta.encoder.layer.0.attention.self.key.bias', 'roberta.encoder.layer.0.attention.self.key.weight', 'roberta.encoder.layer.0.attention.self.query.bias', 'roberta.encoder.layer.0.attention.self.query.weight', 'roberta.encoder.layer.0.attention.self.value.bias', 'roberta.encoder.layer.0.attention.self.value.weight', 'roberta.encoder.layer.0.intermediate.dense.bias', 'roberta.encoder.layer.0.intermediate.dense.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.dense.bias', 'roberta.encoder.layer.0.output.dense.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.dense.bias', 'roberta.encoder.layer.1.attention.output.dense.weight', 'roberta.encoder.layer.1.attention.self.key.bias', 'roberta.encoder.layer.1.attention.self.key.weight', 'roberta.encoder.layer.1.attention.self.query.bias', 'roberta.encoder.layer.1.attention.self.query.weight', 'roberta.encoder.layer.1.attention.self.value.bias', 'roberta.encoder.layer.1.attention.self.value.weight', 'roberta.encoder.layer.1.intermediate.dense.bias', 'roberta.encoder.layer.1.intermediate.dense.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.dense.bias', 'roberta.encoder.layer.1.output.dense.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.dense.bias', 'roberta.encoder.layer.10.attention.output.dense.weight', 'roberta.encoder.layer.10.attention.self.key.bias', 'roberta.encoder.layer.10.attention.self.key.weight', 'roberta.encoder.layer.10.attention.self.query.bias', 'roberta.encoder.layer.10.attention.self.query.weight', 'roberta.encoder.layer.10.attention.self.value.bias', 'roberta.encoder.layer.10.attention.self.value.weight', 'roberta.encoder.layer.10.intermediate.dense.bias', 'roberta.encoder.layer.10.intermediate.dense.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.dense.bias', 'roberta.encoder.layer.10.output.dense.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.dense.bias', 'roberta.encoder.layer.11.attention.output.dense.weight', 'roberta.encoder.layer.11.attention.self.key.bias', 'roberta.encoder.layer.11.attention.self.key.weight', 'roberta.encoder.layer.11.attention.self.query.bias', 'roberta.encoder.layer.11.attention.self.query.weight', 'roberta.encoder.layer.11.attention.self.value.bias', 'roberta.encoder.layer.11.attention.self.value.weight', 'roberta.encoder.layer.11.intermediate.dense.bias', 'roberta.encoder.layer.11.intermediate.dense.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.dense.bias', 'roberta.encoder.layer.11.output.dense.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.dense.bias', 'roberta.encoder.layer.2.attention.output.dense.weight', 'roberta.encoder.layer.2.attention.self.key.bias', 'roberta.encoder.layer.2.attention.self.key.weight', 'roberta.encoder.layer.2.attention.self.query.bias', 'roberta.encoder.layer.2.attention.self.query.weight', 'roberta.encoder.layer.2.attention.self.value.bias', 'roberta.encoder.layer.2.attention.self.value.weight', 'roberta.encoder.layer.2.intermediate.dense.bias', 'roberta.encoder.layer.2.intermediate.dense.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.dense.bias', 'roberta.encoder.layer.2.output.dense.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.dense.bias', 'roberta.encoder.layer.3.attention.output.dense.weight', 'roberta.encoder.layer.3.attention.self.key.bias', 'roberta.encoder.layer.3.attention.self.key.weight', 'roberta.encoder.layer.3.attention.self.query.bias', 'roberta.encoder.layer.3.attention.self.query.weight', 'roberta.encoder.layer.3.attention.self.value.bias', 'roberta.encoder.layer.3.attention.self.value.weight', 'roberta.encoder.layer.3.intermediate.dense.bias', 'roberta.encoder.layer.3.intermediate.dense.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.dense.bias', 'roberta.encoder.layer.3.output.dense.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.dense.bias', 'roberta.encoder.layer.4.attention.output.dense.weight', 'roberta.encoder.layer.4.attention.self.key.bias', 'roberta.encoder.layer.4.attention.self.key.weight', 'roberta.encoder.layer.4.attention.self.query.bias', 'roberta.encoder.layer.4.attention.self.query.weight', 'roberta.encoder.layer.4.attention.self.value.bias', 'roberta.encoder.layer.4.attention.self.value.weight', 'roberta.encoder.layer.4.intermediate.dense.bias', 'roberta.encoder.layer.4.intermediate.dense.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.dense.bias', 'roberta.encoder.layer.4.output.dense.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.dense.bias', 'roberta.encoder.layer.5.attention.output.dense.weight', 'roberta.encoder.layer.5.attention.self.key.bias', 'roberta.encoder.layer.5.attention.self.key.weight', 'roberta.encoder.layer.5.attention.self.query.bias', 'roberta.encoder.layer.5.attention.self.query.weight', 'roberta.encoder.layer.5.attention.self.value.bias', 'roberta.encoder.layer.5.attention.self.value.weight', 'roberta.encoder.layer.5.intermediate.dense.bias', 'roberta.encoder.layer.5.intermediate.dense.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.dense.bias', 'roberta.encoder.layer.5.output.dense.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.dense.bias', 'roberta.encoder.layer.6.attention.output.dense.weight', 'roberta.encoder.layer.6.attention.self.key.bias', 'roberta.encoder.layer.6.attention.self.key.weight', 'roberta.encoder.layer.6.attention.self.query.bias', 'roberta.encoder.layer.6.attention.self.query.weight', 'roberta.encoder.layer.6.attention.self.value.bias', 'roberta.encoder.layer.6.attention.self.value.weight', 'roberta.encoder.layer.6.intermediate.dense.bias', 'roberta.encoder.layer.6.intermediate.dense.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.dense.bias', 'roberta.encoder.layer.6.output.dense.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.dense.bias', 'roberta.encoder.layer.7.attention.output.dense.weight', 'roberta.encoder.layer.7.attention.self.key.bias', 'roberta.encoder.layer.7.attention.self.key.weight', 'roberta.encoder.layer.7.attention.self.query.bias', 'roberta.encoder.layer.7.attention.self.query.weight', 'roberta.encoder.layer.7.attention.self.value.bias', 'roberta.encoder.layer.7.attention.self.value.weight', 'roberta.encoder.layer.7.intermediate.dense.bias', 'roberta.encoder.layer.7.intermediate.dense.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.dense.bias', 'roberta.encoder.layer.7.output.dense.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.dense.bias', 'roberta.encoder.layer.8.attention.output.dense.weight', 'roberta.encoder.layer.8.attention.self.key.bias', 'roberta.encoder.layer.8.attention.self.key.weight', 'roberta.encoder.layer.8.attention.self.query.bias', 'roberta.encoder.layer.8.attention.self.query.weight', 'roberta.encoder.layer.8.attention.self.value.bias', 'roberta.encoder.layer.8.attention.self.value.weight', 'roberta.encoder.layer.8.intermediate.dense.bias', 'roberta.encoder.layer.8.intermediate.dense.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.dense.bias', 'roberta.encoder.layer.8.output.dense.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.dense.bias', 'roberta.encoder.layer.9.attention.output.dense.weight', 'roberta.encoder.layer.9.attention.self.key.bias', 'roberta.encoder.layer.9.attention.self.key.weight', 'roberta.encoder.layer.9.attention.self.query.bias', 'roberta.encoder.layer.9.attention.self.query.weight', 'roberta.encoder.layer.9.attention.self.value.bias', 'roberta.encoder.layer.9.attention.self.value.weight', 'roberta.encoder.layer.9.intermediate.dense.bias', 'roberta.encoder.layer.9.intermediate.dense.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.dense.bias', 'roberta.encoder.layer.9.output.dense.weight', 'roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing BertMultiTaskClassifier from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertMultiTaskClassifier from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-385
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-176] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-770
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-286] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-1155
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-385] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-1540
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-770] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-1925
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-1155] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-2310
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-1540] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-2695
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-1925] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-3080
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-2310] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-3465
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-2695] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-3850
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-3080] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-4235
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-3465] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-4620
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-3850] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-5005
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-4235] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-5390
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-4620] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-5775
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-5005] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-6160
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-5775] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-6545
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-5390] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-6930
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

Deleting older checkpoint [outputs-train/litlatbert-lora-large/checkpoint-6160] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 2640
  Batch size = 128
Saving model checkpoint to outputs-train/litlatbert-lora-large/checkpoint-7315
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [

tokenizer config file saved in outputs/lith_classifier_litlatbert_lora_balanced_groups_full/tokenizer_config.json
Special tokens file saved in outputs/lith_classifier_litlatbert_lora_balanced_groups_full/special_tokens_map.json

sexuality
              precision    recall  f1-score   support

           0       0.81      0.90      0.85       185
           1       0.89      0.78      0.83       184

    accuracy                           0.84       369
   macro avg       0.85      0.84      0.84       369
weighted avg       0.85      0.84      0.84       369

religion
              precision    recall  f1-score   support

           0       0.69      0.56      0.62       183
           1       0.63      0.75      0.69       183

    accuracy                           0.66       366
   macro avg       0.66      0.66      0.65       366
weighted avg       0.66      0.66      0.65       366

country
              precision    recall  f1-score   support

           0       0.76      0.69      0.72        93
           1       0.72      0.79      0.75        94

    accuracy                           0.74       187
   macro avg       0.74      0.74      0.74       187
weighted avg       0.74      0.74      0.74       187

race
              precision    recall  f1-score   support

           0       0.68      0.57      0.62       360
           1       0.63      0.73      0.67       361

    accuracy                           0.65       721
   macro avg       0.65      0.65      0.65       721
weighted avg       0.65      0.65      0.65       721

politics
              precision    recall  f1-score   support

           0       0.65      0.74      0.69       500
           1       0.70      0.60      0.65       499

    accuracy                           0.67       999
   macro avg       0.67      0.67      0.67       999
weighted avg       0.67      0.67      0.67       999

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--EMBEDDIA--litlat-bert/snapshots/0ff2fcc527af01aa224c997f8159b6ede2fdd034/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 84201
}

        task  accuracy  f1_score  precision    recall     kappa   roc_auc
0  sexuality  0.842818  0.832370   0.888889  0.782609  0.685533  0.842656
1   religion  0.655738  0.685000   0.631336  0.748634  0.311475  0.655738
2    country  0.737968  0.751269   0.718447  0.787234  0.475651  0.737703
3       race  0.647712  0.674359   0.627685  0.728532  0.295264  0.647599
4   politics  0.670671  0.646617   0.696759  0.603206  0.341252  0.670603

In [11]:
print("Training finished:", datetime.now())

Training finished: 2026-03-18 12:41:20.996762